name: CI

on:
  workflow_dispatch:
  push:
    branches: [my_tweaks]
    paths-ignore:
      - '.github/**'
      - README.md
  pull_request:
    branches: [my_tweaks]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      VM_PREFIX: vm-megakraken-

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Set short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build
        env:
          SYNC_DROPBOX_CLIENT_ID: ${{ secrets.SYNC_DROPBOX_CLIENT_ID }}
          SYNC_GOOGLE_DESKTOP_ID: ${{ secrets.SYNC_GOOGLE_DESKTOP_ID }}
          SYNC_GOOGLE_DESKTOP_SECRET: ${{ secrets.SYNC_GOOGLE_DESKTOP_SECRET }}
          SYNC_ONEDRIVE_CLIENT_ID: ${{ secrets.SYNC_ONEDRIVE_CLIENT_ID }}
        run: yarn && yarn build && yarn build:crx3 && yarn build:xpi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.VM_PREFIX }}${{ env.SHORT_SHA }}'
          path: 'dist/*'
          if-no-files-found: error

      - name: Prepare files for Github Release
        run: |
          zip -r "${VM_PREFIX}${SHORT_SHA}.zip" dist/*
          mv extension.crx "${VM_PREFIX}${SHORT_SHA}.crx"
          mv extension.xpi "${VM_PREFIX}${SHORT_SHA}.xpi"

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.SHORT_SHA }}
          name: ${{ env.SHORT_SHA }}
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            ${{ env.VM_PREFIX }}${{ env.SHORT_SHA }}.zip
            ${{ env.VM_PREFIX }}${{ env.SHORT_SHA }}.crx
            ${{ env.VM_PREFIX }}${{ env.SHORT_SHA }}.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
